FROM node:lts-alpine

# Install dependencies
RUN apk add --no-cache postgresql-client

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./
# Install dependencies
RUN npm install --loglevel=error

#copy entire app
COPY . .
ENV NODE_ENV=production

EXPOSE 5000
RUN npm install -g gulp-cli
RUN npm install -g gulp
RUN chown -R node /usr/src/app
USER node
CMD ["npm", "run", "backend-build"]
